### ISSUE TITLE
Why not use memoryStore in production?

### ISSUE THREAD

**Issue by MichaelJCole** [AdamPflug/express-brute#10]
```
var store = new ExpressBrute.MemoryStore(); // stores state locally, don't use this in production
```
The only two downsides I see are:

1) Rebooting clears any limits.
2) Node.js clusters and load balanced servers don't share state

Both of which seem like false negatives.  If I can save a request to Redis and the complexity, that's a win for me.

Other drawbacks?  Does it leak memory over time?  Thanks!

**Comment by AdamPflug** [comment]
You hit the nail on the head for the downsides. The second one is particularly an issue because it tends to be easier to get node servers to restart than other servers in my experience (if you can cause an un-caught exception then you can bypass the brute force protections).

The only "memory leak" is that it stores the request history in ram, and uses setTimeout for each ip to clean it up after the the lifetime is over. I haven't tested large numbers of setTimeout calls with node (other people have it looks like http://stackoverflow.com/questions/12168708/is-there-any-limit-to-settimeout) so I wasn't sure if that would cause issues. If you didn't have a lifetime set then it would leak memory over time because it would never clean up the list. Also setTimeout would have issues if you had extremely large lifetimes (e.g. over 24.8 days). There probably should be a range check in there to prevent that... I'll look at a patch. Realistically this probably isn't a huge issue because we're not store much data and it shouldn't be possible to spoof IP addresses for TCP packets.

Long-story-short, If you are in an single-threaded environment, and are confident in your error handling, and set a reasonable lifetime, then it's probably fine. I just wanted to make sure people thought about it before simply using MemoryStore just because that's what I used in the examples. If you think there is a better way to talk about this in the README feel free to change it and submit a PR.

**Comment by MichaelJCole** [comment]
Thanks for the clarification.  Exactly what I was looking for :-)
