### ISSUE TITLE
DynamoDB adapter for the express-brute middleware

### ISSUE THREAD

**Issue by supaggregator** [AdamPflug/express-brute#26]
Hello, I have written a dynamoDB adapter for express-brute middleware. I'm new to programming especially to node.js, so the codes maybe look like naif. I'm very glad to receive your comments, thanks.

Duo XU

PS. Links :
https://www.npmjs.com/package/express-brute-dynamo
https://github.com/supaggregator/express-brute-dynamo

**Comment by AdamPflug** [comment]
Obviously not a full code review, but a couple of thoughts:
* I think calling `clean` should happen in plugin itself. You could make the interval configurable with parameter to the constructor. Also, you shouldn't need to call it until at least 'lifetime' has passed since the first 'set'.
* You should probably have some concurrency stuff set in `clean`, if there are multiple processes going at once you'll have a lot of "duplicate" deletes.
* If you update a count/expire date between when an item is marked for deletion and it is actually deleted you'll lose that update.

I'll add it to the list if you want though.
