### ISSUE TITLE
Few questions on status / latest version?

### ISSUE THREAD

**Issue by ErisDS** [AdamPflug/express-brute#39]
I'm looking at using this module in several projects, and wanted to check in beforehand 👋

Is this module still maintained and/or used in production by anyone? It seems like this is the most established set of middleware for brute force prevention, or is there an alternative I'm missing?

Also, which is the correct/latest version to use?

I'm a little confused as, in the readme it has some documentation about v1.0.0, but the latest version on npm is 0.7.0-beta.0 which was published 2 months ago. Is the beta safe to use? 

Finally, I noticed this module depends on underscore, would there be any interest in switching to lodash as that is more common nowadays in my experience. Not a big deal, just wondering 🤔

Thanks for reading! :)

**Comment by AdamPflug** [comment]
I'm still maintaining it, although It's not under heavy development at the moment (I'm waiting on that until I get the time to build a Koa version and factor out their common code as a dependency. I'm also hoping they can use the same adapters).

We get about 6k installs a month, which I think is the most for any of the brute force prevention middleware I'm aware of. I've used it in production and others have as well. 

My bad on the version numbering. I created 0.7.0-beta.0 a while ago, but then decided it was better to call it 1.0.0 on release because there were some changes that weren't backwards compatible (semver). I updated the documentation but hadn't rolled it out via NPM yet. 1.0.0 should be out now for you.

I don't have anything against migrating to lodash, I'd merge the pull request if one came in, but I don't really see a reason to make the change right now since it's been working.

**Comment by ErisDS** [comment]
👍  Thanks for the quick & detailed reply 

The version mismatch made it seem like the module might have died for some reason (e.g. there was some new alternative) but npm certainly makes this look like the right choice 😁 

Thanks for pushing a 1.0.0 version. I also agree there's little benefit to going out of the way to swap underscore for lodash, I was just slightly surprised to see underscore and wondered if there might be a reason. I wonder about things a lot 🍰

**Comment by AdamPflug** [comment]
No problem :)

If I were starting today I'd use lodash, but in 2013 it was still pretty new and I had lots of experience with underscore hehe.
