### ISSUE TITLE
handleStoreError not always called with next

### ISSUE THREAD

**Issue by kirrg001** [AdamPflug/express-brute#45]
Hey 👋

We are using express-brute, but we experienced that `handleStoreError` is not always called with a passed callback.

See https://github.com/AdamPflug/express-brute/blob/master/index.js#L156

So when calling reset and we pass a callback and a `handleStoreError` is present, then it would be great forwarding the callback. (next: callback)

Thank you!

**Comment by AdamPflug** [comment]
So for most of the store errors we're setting `next` to the next middleware in the chain, but in the case of `reset` that doesn't make sense (because `reset` can be called outside the context of a request). Are you wanting just to set a separate `callback` property in that case? That seems reasonable, but I don't think setting `next` to the callback really makes sense because it's not really continuing the a request (or at least not always). 

Pull requests always appreciated :)

**Comment by kirrg001** [comment]
> Pull requests always appreciated :)

Will create a PR 👍 But before i do, i have one last question.

Why is `handleStoreError` called for `reset` at all?Thanks for your help :)

**Comment by AdamPflug** [comment]
`handleStoreError` can be called from `reset` because `reset` needs to clear the key in the store (which could potentially error out).
