### ISSUE TITLE
Why isn't MemoryStore ready for production?

### ISSUE THREAD

**Issue by MichaelTSS** [AdamPflug/express-brute#63]
From README.md
> ExpressBrute.MemoryStore()
> An in-memory store for persisting request counts. Don't use this in production, instead choose one of the more robust store implementations listed below.

[The express-throttle package](https://www.npmjs.com/package/express-throttle) relies on a [LRU cache](https://github.com/isaacs/node-lru-cache), a not-so-simple algorithm that is pretty good at what it does.

**Comment by AdamPflug** [comment]
The current memory store is basically the simplest implementation I could think of that had the correct behavior for people to use while testing - it basically just stores data as properties on an object and deletes those keys with `setTimeout` when they are no longer needed. There are two big issues with this in production:

1. It doesn't share state across multiple processes or servers (so it doesn't scale well horizontally)
2. It uses more memory the more traffic the process handles, which could cause the server to run out of RAM (so it doesn't scale well vertically).

If you don't have a lot of concurrent transactions (and especially if your values of `lifetime` are low) it's probably fine in production, but it just doesn't scale well.

An LRU implementation would probably be better in production because it puts an upper limit on the memory usage which solves second problem (although at the cost of possibly being overly permissive in high traffic cases - because it essentially "forgets" about the least used records, possibly earlier than it should). Unfortunately it doesn't really address the 1st problem (as noted on the [express-throttle page under "limitations"](https://www.npmjs.com/package/express-throttle#limitations)) There's nothing stopping someone from developing an LRU store for express brute, but I personally chose not to invest the time because I am more interested in solutions which solve the 1st problem as well (multi-process/server support).

FYI, some people have developed adapters that use a couple of different node.js in-memory databases under the hood - so that's another option you could look into as well:
* https://github.com/Requarks/express-brute-loki
* https://github.com/natsukagami/express-brute-nedb

**Comment by MichaelTSS** [comment]
Hey @AdamPflug,

First of all, thank you for the quick, complete and educational response. Makes one love OSS more than ever!

I have looked into the two stores you mentioned but they won't do the trick as they add dependencies that are not light, plus they don't seem to have a settable cap for memory. I think I'll go for the express-throttle package for now as I am using my node server as single process. I don't need strong consistency for old values so I should be fine for now.

Best,
