### ISSUE TITLE
error handling for store.get

### ISSUE THREAD

**Issue by zoellner** [AdamPflug/express-brute#8]
I'm using express-brute with express-brute-mongo. I see occasions when the mongoDB call returns an error (possibly a timeout). This then doesn't get handled smoothly in express-brute/index.js L83-85 and crashes my node instance. I think this should at least pass on the actual error for debugging purposes

    this.store.get(key, _.bind(function (err, value) {
      if (err) {
        throw "Cannot get request count";
      }

**Comment by AdamPflug** [comment]
Yeah, that's a good point. I'm working on a fix that would:

1. Include the original error in the error object that gets thrown
2. Allow you to pass your own function to handle store errors if one occurs (and you don't want the error just thrown).

I think for most users having the error thrown is probably the correct answer because a server restart will probably fix the problem, and there is nothing we can do to recover from the error. That said, this is absolutely be a behavior that people should have more control over.

I'm committing it to master now, but I'm still working on tests and such.

Let me know if that sounds like it would solve your issue,

- Adam

**Comment by zoellner** [comment]
Yes, that sounds exactly like what I would need.
Thank you!

**Comment by AdamPflug** [comment]
This should be resolved in v0.5.3 - let me know if you have any issues!

- Adam

**Comment by llambda** [comment]
@AdamPflug thank you for this, very nice!
