### ISSUE TITLE
Possible bug in freeRetries count condition 

### ISSUE THREAD

**Issue by jhnferraris** [AdamPflug/express-brute#82]
I have a request which only has 3 `freeRetries` but on the 4th request it is still not responding a 429. Debugging the condition in freeRetries count in https://github.com/AdamPflug/express-brute/blob/bc48c35f04d4a09738ff7596f0c6fe4757a22e4a/index.js#L126, the actual `count` starts from 0. 

Logging the line `console.log(count, '<=',  this.options.freeRetries)`seems the behavior is:

```
Request 1:
0 <= 3
Request 2:
1 <= 3
Request 3:
2 <= 3
Request 4: // It should fail here
3 <=3
```

Since the 4th retry the count equals to  this.options.freeRetries, the request still proceeds. 
I implemented a workaround in my side to set the expressBrute middleware retries to `freeRetries - 1` just to let it pass.

What would be the best approach to this?

1. Set the initial `count` to 1?
2. Modify the condition to `count < this.options.freeRetries`

Let me know your thoughts.

**Comment by AdamPflug** [comment]
So this is intended, but maybe it's confusing wording. The parameter is named `freeRetries`, and the first request is not considered a "retry". It made more sense to me because setting `freeRetries` to 0 still is a valid use case, but if you made it just `freeAttempts` or something and then someone set it to 0 it basically breaks all requests going through the middelware (you have to have the option to try at least once or it will always fail). True you can still run into this issue by passing a negative number for `freeRetries`, but that's more obviously wrong.
