### ISSUE TITLE
Query: Can you give an example of a fibonacci type delay ?

### ISSUE THREAD

**Issue by puneetmakkar** [AdamPflug/express-brute#88]

**Comment by AdamPflug** [comment]
It just means that the minimum time between 2 allowed requests after your free retries are used grows similar to the Fibonacci sequence (the minimum delay for any request is equal to the sum of the minimum delays for the previous 2 requests).

In practice this interacts with minWait and maxWait so that the effective minimum time between requests after free retries are used is `[minWait*1, minWait*1, minWait*2, minWait*3, minWait*5, minWait*8, minWait*13, minWait*21, ...]` Increasing until you reach maxWait. In this way it's only fibobacci-like because the actual delays are not necessarily numbers on the Fibonacci sequence and because there is a maximum delay amount.

**Comment by puneetmakkar** [comment]
Thanks @AdamPflug for the explanation.

**Comment by puneetmakkar** [comment]
@AdamPflug 
```javascript
const authApiBrute = new ExpressBrute(authStore, {
      freeRetries: 10,
      minWait: 60 * 1000, // 60 sec
      maxWait: 3600 * 1000, // 1 hour
      refreshTimeoutOnRequest: false
    });
```

questions) How does the package keeps track that the ip has waited for maxWait and what happens when you reach maxWait ? In redis, I only see IP, first and last request. When do we reset the entry in redis ? We don't need to have lifetime in this scenario ?

I have an entry in redis which is a day old and hasn't been removed for a particular IP.
