### ISSUE TITLE
Stores are not consistently sync/async

### ISSUE THREAD

**Issue by joepie91** [AdamPflug/express-brute#9]
Right now, the `MemoryStore` implements [synchronous callbacks](https://github.com/AdamPflug/express-brute/blob/master/lib/MemoryStore.js#L27) whereas other modules typically use asynchronous callbacks. In order to make it possible to reason about the code flow, these should be consistently asynchronous (eg. using `process.nextTick` or `setImmediate`).

More about this can be found in [this article](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony).

**Comment by AdamPflug** [comment]
Right now MemoryStore is basically just a Mock that I use for testing, and it's easier to use in that manner if it's synchronous (although my test coverage is probably not technically as good). It's really just for testing during development, it doesn't work at all in clustered deployments so it's not really production ready in my mind.

The synchronous vs async callbacks issue is really a bigger deal for threaded environments. As a general rule of thumb I feel like code that this behavior would break is bad, I can't think of an example (in node) where you couldn't just change the order of statements in order to account for immediate execution of the callback, and I think the other order (callback at the end) is easier to read.

That said, fixing it doesn't really hurt anything, and does prevent some possible bugs in apps people write using this. I would welcome a pull request if you have one, not sure when I'll get around fixing it just because I would likely need to re-work the tests to account for the async execution.

- Adam

**Comment by joepie91** [comment]
> Right now MemoryStore is basically just a Mock that I use for testing, and it's easier to use in that manner if it's synchronous (although my test coverage is probably not technically as good). It's really just for testing during development, it doesn't work at all in clustered deployments so it's not really production ready in my mind.

Right, but even then this matters - see the article I linked. If one uses the MemoryStore during development and then replaces it with a different store in production, their code could break in production due to the difference in code execution behaviour.

> The synchronous vs async callbacks issue is really a bigger deal for threaded environments.

Quite the contrary! [This gist](https://gist.github.com/joepie91/98576de0fab7badec167) demonstrates the issue. It is applicable to any asynchronous environment, threaded or not.

> As a general rule of thumb I feel like code that this behavior would break is bad, I can't think of an example (in node) where you couldn't just change the order of statements in order to account for immediate execution of the callback, and I think the other order (callback at the end) is easier to read.

The stores are supposed to be a 'black box' - they store your data *somehow*, but you shouldn't have to care about specifically *how* they store it. Having to change your code to account for differences in sync/async operation between stores, just makes it a leaky abstraction.

> That said, fixing it doesn't really hurt anything, and does prevent some possible bugs in apps people write using this. I would welcome a pull request if you have one, not sure when I'll get around fixing it just because I would likely need to re-work the tests to account for the async execution.

I could send a pull request, but as I don't normally write automated tests, I would be unable to include asynchronous tests :)

**Comment by Magnitus-** [comment]
>That said, fixing it doesn't really hurt anything, and does prevent some possible bugs in apps people write using this. I would welcome a pull request if you have one, not sure when I'll get around fixing it just because I would likely need to re-work the tests to account for the async execution.<

>I could send a pull request, but as I don't normally write automated tests, I would be unable to include asynchronous tests :)<

I can do it once my current pull request is resolved.

**Comment by AdamPflug** [comment]
So, I've looked into this a bit in the mean-time, and I have a few more thoughts. Whether or not MemoryStore is actually consistently sync/async doesn't really matter because it's only meant to be called by ExpressBrute internals anyway, so it shouldn't affect end users. Likewise, whether ExpressBrute, as a middleware, calls `next()` immediately or not shouldn't have any impact on end user code. The only place I can think of where we run into issues is with the `reset` methods (both the one attached to `req.brute.reset` and the one on the ExpressBrute instance itself).

Because changing all of the MemoryStore calls to be consistently async requires almost all of the unit tests to be re-written (they are relying on the fact that it isn't to make testing easier). So far I've taken the half-step of just ensuring `reset` is consistently async. I think this addresses most of the end-user impact.

Having the tests fully async (as would be required to change MemoryStore calls to async) would definitely be better - but it would add enough complexity to testing that I'm punting on it right now. This is especially true because between jasmine 1 and jasmine 2 they are re-working how async testing works - and because I'd really like to switch to Mocha/Chai/Sinon at some point (which uses the 2.0 syntax).
